collections:
- name: cisco.aci
- name: cisco.asa
- name: cisco.cml
- name: cisco.ios
- name: cisco.iosxr
- name: cisco.nxos
- name: cisco.ucs
- name: ansible.netcommon
- name: ansible.posix
- name: ansible.utils
- name: community.crypto
- name: community.docker
- name: community.general
- name: community.hashi_vault
- name: community.libvirt
- name: community.network
- name: community.proxmox
- name: community.routeros
- name: community.vagrant
- name: community.yang
- name: containers.podman
- name: grafana.grafana
- name: networktocode.nautobot
- name: check_point.gaia
- name: check_point.mgmt
